server:
  port: 9000
spring:
  application:
    name: Sci-Management
  datasource:
    url: jdbc:mysql://localhost:3306/sci?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    database: 0
    #host: 8.134.129.167
    #password: 542245
    host: localhost
    lettuce:
       pool:
         max-active: 10
         max-idle: 10
         min-idle: 1
mybatis-plus:
  type-aliases-package: com.sci.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false