server:
  port: 9000
spring:
  application:
    name: Sci-Management
  datasource:
    url: jdbc:mysql://www.schurfroggy.cn:3306/sci?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  data:
    redis:
      database: 0
      port: 6379
      host: 8.134.129.167
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
mybatis:
  type-aliases-package: com.sci.entity
